"""
Students service: reads the precomputed roster (app/data/students_sample.json)
generated by scripts/generate_sample_students.py, and supports simple filtering.

This file is loaded once at import time (module-level, same "load once"
principle as the model itself) rather than re-reading the JSON file from
disk on every single request.
"""
import json
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "students_sample.json"

_students_cache = None


def _load_students():
    global _students_cache
    if _students_cache is None:
        if not DATA_PATH.exists():
            raise FileNotFoundError(
                f"Sample student data not found at {DATA_PATH}. "
                f"Run backend/scripts/generate_sample_students.py first."
            )
        with open(DATA_PATH) as f:
            _students_cache = json.load(f)
    return _students_cache


def get_students(risk_band: str = None, course: int = None, limit: int = None):
    """
    Returns the student list, optionally filtered.
    risk_band: "High" | "Medium" | "Low" — exact match, case-insensitive.
    course: exact course code match.
    limit: cap the number of results returned (e.g. for a paginated table).
    """
    students = _load_students()

    if risk_band:
        students = [s for s in students if s["risk_band"].lower() == risk_band.lower()]
    if course is not None:
        students = [s for s in students if s["course"] == course]
    if limit:
        students = students[:limit]

    return students


def get_student_by_id(student_id: str):
    students = _load_students()
    for s in students:
        if s["student_id"] == student_id:
            return s
    return None
