export default function About() {
  return (
    <div style={{ maxWidth: 720 }}>
      <h1>About EduPulse</h1>

      <Section title="The Problem">
        <p>
          Universities often have thousands of students but limited academic-advising
          capacity. By the time a student's struggle becomes obvious, intervention can
          come too late. EduPulse explores whether historical enrollment and academic
          data can help surface risk earlier, so a human advisor can reach out sooner —
          not so a system can act on a student's behalf.
        </p>
      </Section>

      <Section title="Dataset & Credit">
        <p>
          Predictions are generated by a model trained on the UCI Machine Learning
          Repository dataset <em>"Predict Students' Dropout and Academic Success"</em>{" "}
          (4,424 records, 36 features, DOI 10.24432/C5MC89). The dataset was retrieved
          via a verified public mirror during development — full retrieval and
          verification notes are documented in <code>ml/data/SOURCE.md</code> in the
          project repository.
        </p>
      </Section>

      <Section title="How Predictions Work">
        <p>
          A student's record is passed through a single serialized preprocessing and
          model pipeline — the same pipeline used during training, so there is no
          mismatch between how the model was built and how it makes live predictions.
          The model outputs a probability for each of three outcomes (Dropout, Enrolled,
          Graduate). SHAP is used to compute which features most influenced that specific
          prediction.
        </p>
      </Section>

      <Section title="Limitations">
        <ul style={{ color: "var(--ink-soft)", paddingLeft: 20 }}>
          <li>
            Overall test accuracy is roughly 74–78% and macro-F1 is roughly 0.70,
            depending on which model wins cross-validation (see Model Insights) — this
            is a useful decision-support signal, not a certainty.
          </li>
          <li>
            The "Enrolled" outcome is the hardest for the model to predict — it has the
            fewest training examples and behaviorally overlaps with both other classes.
          </li>
          <li>
            The model was trained on one historical dataset from one country's higher
            education system. Its accuracy is not guaranteed to hold for other
            institutions, time periods, or student populations.
          </li>
          <li>
            Global feature importance can be inflated for high-cardinality categorical
            features (e.g. occupation codes with 40+ categories) due to how one-hot
            encoded contributions are aggregated back to the original feature.
          </li>
        </ul>
      </Section>

      <Section title="Responsible Use">
        <div className="card" style={{ borderColor: "var(--accent)", background: "var(--accent-soft)" }}>
          <p style={{ margin: 0, color: "var(--ink)" }}>
            EduPulse is a decision-support prototype for human academic advisors. It must
            not be used to automatically remove, penalize, reject, rank, or discipline
            students. A prediction and its explanation describe patterns the model found
            in historical data — they do not prove that any single factor caused a
            student's outcome, and they should never replace a human conversation with
            the student.
          </p>
        </div>
      </Section>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2>{title}</h2>
      {children}
    </div>
  );
}
